import { TeamMember, Resource, Committee } from './types';

export const SECRETARIAT: TeamMember[] = [
  {
    id: '1',
    name: 'Lea',
    position: 'Secretary General',
    quote: 'i understand why MUNers retire early now',
    image: '/team/afzan-azmin.jpeg',
    category: 'Core',
  },
  {
    id: '2',
    name: 'Sachinn',
    position: 'Deputy Secretary General',
    quote: '\ud83d\udc4b',
    image: '/team/sachinn.jpeg',
    category: 'Core',
  },
  {
    id: '3',
    name: 'Izaac',
    position: 'Secretary',
    quote: 'Benjamin caught a fish in a net and said: "Yahoo!". This is all real BTW.',
    image: '/team/izaac-lau.jpeg',
    category: 'Core',
  },
  {
    id: '4',
    name: 'Afzan',
    position: 'Advisor',
    quote: '',
    image: '/team/afzan.jpeg',
    category: 'Core',
  },
  {
    id: '5',
    name: 'Aron Choi',
    position: 'Head of Finance',
    quote: '',
    image: '/team/aron.png',
    category: 'Finance',
  },
  {
    id: '6',
    name: 'Vridhi',
    position: 'Head of Conference Affairs',
    quote: '',
    image: '/picture.jpeg',
    category: 'Conference',
  },
  {
    id: '7',
    name: 'Sean',
    position: 'Head of Academics',
    quote: 'is this tuff???',
    image: '/team/sean-aariz-shahrul.jpeg',
    category: 'Academics',
  },
  {
    id: '8',
    name: 'Vyncus Lim',
    position: 'Head of IT',
    quote: 'Every clause carries intention; every decision shapes consequence.',
    image: '/team/vyncus-lim.jpeg',
    photos: [
      '/team/vyncus-lim.jpeg',
      '/team/vyncus/dubai-sign.jpeg',
      '/team/vyncus/dubai-frame.png',
      '/team/vyncus/traditional-lane.png',
    ],
    category: 'IT',
    linkedin: 'https://www.linkedin.com/in/vyncus-lim-761300375/',
    instagram: 'https://www.instagram.com/vyncuslim',
    website: 'https://sleepsomno.com',
    bio: `Vyncus Lim serves as Head of IT for POWIIS MUN 2027, helping shape the conference's digital presence and technical direction with precision and intent.`,
  },
  {
    id: '9',
    name: 'Hayley Guan',
    position: 'Head of Marketing',
    quote: '...',
    image: '/team/hayley-guan.jpeg',
    category: 'PR',
  },
  {
    id: '10',
    name: 'Sabari Laxmi',
    position: 'member of finance',
    quote: 'The only means of fighting a plague is - common decency',
    image: '/team/sabari-laxmi.jpeg',
    category: 'Finance',
  },
  {
    id: '11',
    name: 'Rio Law',
    position: 'member of academics',
    quote: 'Vision without execution is just hallucination - light bulb guy',
    image: '/team/rio-law.jpeg',
    category: 'Academics',
  },
  {
    id: '12',
    name: 'Sin Yi',
    position: 'member of marketing/design',
    quote: 'Negotiating peace... or at least group project deadlines.',
    image: '/team/sin-yi.jpeg',
    category: 'PR',
  },
  {
    id: '13',
    name: 'Rae En Chang',
    position: 'member of academics and marketing/design',
    quote: 'Aspire to inspire before you expire',
    image: '/team/rae-en-chang.jpeg',
    category: 'PR',
  },
  {
    id: '14',
    name: 'Glavelle Yeoh',
    position: 'member of finance',
    quote: 'anyone, from anywhere, can do anything',
    image: '/team/glavelle-yeoh.jpeg',
    category: 'Finance',
  },
  {
    id: '15',
    name: 'Rin Fujita',
    position: 'member of conference affairs',
    quote: 'Memorize to improve, improvise to survive',
    image: '/team/rin-fujita.jpeg',
    category: 'Conference',
  },
  {
    id: '16',
    name: 'Dhareni Subramaniam',
    position: 'member of marketing/design',
    quote: 'Gimme some pani puris',
    image: '/team/dhareni-subramaniam.jpeg',
    category: 'PR',
  },
  {
    id: '17',
    name: 'Saisa Sedhai',
    position: 'member of marketing/design',
    quote: 'uh im saisa',
    image: '/team/saisa-sedhai.jpeg',
    category: 'PR',
  },
  {
    id: '18',
    name: 'Hyuna ( Sophie ) Chang',
    position: 'member of conference affairs',
    quote: 'Be the change that you wish to see in the world',
    image: '/team/hyuna-sophie-chang.jpeg',
    category: 'Conference',
  },
  {
    id: '19',
    name: 'Wei Jun',
    position: 'member of conference affairs',
    quote: 'Stars cant shine without brightness',
    image: '/team/wei-jun.jpeg',
    category: 'Conference',
  },
];

export const RESOURCES: Resource[] = [
  {
    id: 'r1',
    title: 'Study Guide',
    description: 'Comprehensive guide for your committee topics.',
    link: '#',
  },
  {
    id: 'r2',
    title: 'Rules of Procedure',
    description: 'The formal rules for debate and resolution.',
    link: 'https://www.myadp.org/_files/ugd/88a5d7_99175ae8edb149f18b59a801eeef90bd.pdf',
  },
  {
    id: 'r3',
    title: 'Country Matrix',
    description: 'List of available countries for each committee.',
    link: '#',
  },
  {
    id: 'r4',
    title: 'Delegate Handbook',
    description: 'Everything you need to know for the conference day.',
    link: '#',
  },
  {
    id: 'r5',
    title: 'Position Paper Guide',
    description: 'Learn how to write a compelling position paper.',
    link: '#',
  },
  {
    id: 'r6',
    title: 'Resolution Writing',
    description: 'A guide to drafting and submitting resolutions.',
    link: '#',
  },
];

export const COMMITTEES: Committee[] = [
  {
    id: 'c1',
    name: 'UNSC',
    topic: 'The Situation in the South China Sea',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&h=400&auto=format&fit=crop',
    chairs: ['Vyncus Lim', 'Sachinn'],
    description: 'The United Nations Security Council (UNSC) is one of the six principal organs of the United Nations, charged with ensuring international peace and security.',
  },
  {
    id: 'c2',
    name: 'ECOSOC',
    topic: 'Addressing the Global Debt Crisis in Developing Nations',
    image: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=800&h=400&auto=format&fit=crop',
    chairs: ['Sean Aariz Shahrul', 'Glavelle Yeoh'],
    description: 'The Economic and Social Council (ECOSOC) is the principal body for coordination, policy review, policy dialogue and recommendations on economic, social and environmental issues.',
  },
  {
    id: 'c3',
    name: 'UNHRC',
    topic: 'Protecting the Rights of Refugees and Internally Displaced Persons',
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=800&h=400&auto=format&fit=crop',
    chairs: ['Afzan Azmin', 'Sachinn'],
    description: 'The United Nations Human Rights Council (UNHRC) is a United Nations body whose mission is to promote and protect human rights around the world.',
  },
  {
    id: 'c4',
    name: 'UNODC',
    topic: 'Combating Transnational Organized Crime and Illicit Drug Trafficking',
    image: 'https://images.unsplash.com/photo-1523292562811-8fa7962a78c8?q=80&w=800&h=400&auto=format&fit=crop',
    chairs: ['Vyncus Lim', 'Izaac Lau'],
    description: 'The United Nations Office on Drugs and Crime (UNODC) is a global leader in the fight against illicit drugs and international crime.',
  },
  {
    id: 'c5',
    name: 'IPC',
    topic: 'International Press Corps (Reporting on the Conference)',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=800&h=400&auto=format&fit=crop',
    chairs: ['Glavelle Yeoh', 'Afzan Azmin'],
    description: 'The International Press Corps (IPC) is responsible for documenting and reporting on the proceedings of the conference.',
  },
];

export const GALLERY = [
  'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=800&auto=format&fit=crop',
];

export const SCHEDULE = [
  {
    day: 'Day 1',
    date: 'Jan 15, 2027',
    events: [
      { time: '08:30 - 09:30', title: 'Registration & Breakfast' },
      { time: '09:30 - 10:30', title: 'Opening Ceremony' },
      { time: '10:30 - 12:30', title: 'Committee Session I' },
      { time: '12:30 - 13:30', title: 'Lunch Break' },
      { time: '13:30 - 15:30', title: 'Committee Session II' },
      { time: '15:30 - 16:00', title: 'Tea Break' },
      { time: '16:00 - 17:30', title: 'Committee Session III' },
    ],
  },
  {
    day: 'Day 2',
    date: 'Jan 16, 2027',
    events: [
      { time: '09:00 - 11:00', title: 'Committee Session IV' },
      { time: '11:00 - 11:30', title: 'Tea Break' },
      { time: '11:30 - 13:00', title: 'Committee Session V' },
      { time: '13:00 - 14:00', title: 'Lunch Break' },
      { time: '14:00 - 16:00', title: 'Committee Session VI' },
      { time: '16:00 - 18:00', title: 'Social Event' },
    ],
  },
  {
    day: 'Day 3',
    date: 'Jan 17, 2027',
    events: [
      { time: '09:00 - 11:00', title: 'Committee Session VII' },
      { time: '11:00 - 11:30', title: 'Tea Break' },
      { time: '11:30 - 13:00', title: 'Committee Session VIII' },
      { time: '13:00 - 14:00', title: 'Lunch Break' },
      { time: '14:00 - 16:00', title: 'Closing Ceremony' },
    ],
  },
];
